server:
  port: 8002

spring:
  application:
    name: springcloud-payment-server-hystrix


#Eureka
eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #试服从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true

    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true #显示IP地址