server:
  port: 8001

spring:
  application:
    name: springcloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 13258101219

#整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ang.springcloud.entities

#Eureka
eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #试服从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true

    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001 #修改显示的服务名
    prefer-ip-address: true #显示IP地址
    #eureka客户端向服务端发送心跳的时间间隔单位：s 默认30s
    lease-renewal-interval-in-seconds: 1
