server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    #false表示不香注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/,http://eureka7002.com:7002/